participants:
  - Pete Trabucco, interviewee
  - Jay Young, presenter
interview-date: 2025-03-02
language: en
audio-file: short-interview.ogg
prompt: >
  Pete Trabucco interview on "DayBreak"
  with Jay Young on the USA Radio Network.